<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
format_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags ~@wip"
%>
default: <%= std_opts %> features
wip: --tags @wip:5 --wip features
broken: <%= format_opts %> --strict --tags @broken features
unbroken: <%= format_opts %> --strict --tags ~@broken features
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip
